### PR TITLE
Update getting started to zeebe version 1.1.0

### PR DESCRIPTION
**Pull request by korthout**
Since it was still focused on pre 1.0 releases, some additional work was needed:

- switch to camunda-cloud packages
- replace Workflow with Process
- update links
- build new version

### CODE REVIEW

**Comment by Sijoma** [comment]
Awesome. 🚀 I was about to create an issue exactly for this.

**Comment by npepinpe** [comment]
We archived the Java one a while back as it was superseded by the new getting started guide. Any reason why the Go one is not archived @menski ? I see there's no Go section in the new getting started guide - what's the mid/long term plan?

**Comment by menski** [comment]
The reason is that I didn't migrate the go guide to the new guides, i.e. didn't had time around GA release. Mid term we should also migrate the go client to the new repo. So instead of updating this guide we can also migrate it instead.

**Comment by korthout** [comment]
>So instead of updating this guide we can also migrate it instead.

@menski Does this block merging this PR for now?

**Comment by korthout** [comment]
ping @menski @npepinpe

**Review by npepinpe — APPROVED** [review]
:+1: 

We should not further update this guide and instead expand the new, consolidated getting started guide.

**Comment by korthout** [comment]
>We should not further update this guide and instead expand the new, consolidated getting started guide.

@npepinpe Are you sure about that? This repo is still referenced in the current latest documentation: https://docs.camunda.io/docs/apis-clients/go-client/get-started/
>You can find the complete source code on [GitHub](https://github.com/zeebe-io/zeebe-get-started-go-client).

**Comment by npepinpe** [comment]
I am sure that this is what we should do in the long run, yes :smile: There's not much value in having a separate repo for the Go getting started, but I'm happy to be proven wrong.

**Pull request merged**
